import type { Metadata } from 'next'
import Image from 'next/image'
import waves from '../../public/images/waves.svg'
import styles from './layout.module.css'
import './globals.css'

export const metadata: Metadata = {
  title: 'Movie quiz',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <div className={styles.header}>
          <Image alt="Header background" src={waves} className={styles.image} />
        </div>
        {children}
      </body>
    </html>
  )
}
